- .github/workflows/publish-github-pages.yml
- package.json
- yarn.lock
Master to be published on push at https://veedubyou.github.io/chord-paper-fe/
> Add Publishing to Github Pages

- src/common/ChordModel.ts
- src/components/ChordPaper.tsx
- src/components/ChordPaperMenu.tsx
Skipping tests for this one for now since it's relatively simple, and the menu is currently in flux.
> New song button

- .github/workflows/publish-github-pages.yml
- package.json
- yarn.lock
Setting home pages caused routing specific for all builds - try to use this specific build config for just github pages' build.
> Make build path specific for github pages

- src/components/ChordPaperMenu.tsx
Default to the title for the saved filename.
> Save song as title.json

- src/components/SideMenu.tsx
Changing the links to be relative so the app can mount on a subdirectory
> Menu bug: change absolute links to relative

- src/App.tsx
- src/components/SideMenu.tsx
Using basepath from public url environment to inform relativeness. Hope this works.
> Relative links pt 2

- src/components/Block.tsx
- src/components/ChordSymbol.tsx
> CSS for chord outlining

- src/App.tsx
- src/components/SideMenu.tsx
2 minor changes: clicking title goes back to home, and hashrouter doesn't use the basepath anymore.
> Minor Improvements

- src/components/Block.tsx
- src/components/ChordSymbol.tsx
The design looks nicer now, but the code is dogshit
> Making code awful

- src/App.tsx
- src/components/SideMenu.tsx
- src/components/TextInput.tsx
- src/components/tutorial/AddLine.tsx
- src/components/tutorial/Playground.tsx
- src/components/tutorial/Tutorial.tsx
- src/test/lyrics.test.tsx
Which include fixing paste handling for Chrome on Windows.
> Fixing some tutorial bugs

- package.json
- src/components/Block.tsx
- src/components/ChordSymbol.tsx
- src/components/Line.tsx
- src/components/Lyric.tsx
Pull lyric typography variant into a constant so that all the font sizes are aligned
> Refactor lyric typography

- src/App.tsx
- src/components/Version.tsx
Just small adjustments by using more idiomatic declarations of e.g. font sizes
> minor changes to version component

- src/components/Header.tsx
Match the header according to design
> Designed Header

- src/components/Tutorial.tsx
Accidentally added the DND tutorial in the wrong order, adjusting the placement.
> Fix DND Tutorial ordering

- src/App.tsx
- src/components/SideMenu.tsx
Add expand/collapse buttons to menu
> Collapsible Menu

- src/components/Tutorial.tsx
- src/components/display/Lyric.tsx
- src/components/edit/TextInput.tsx
- src/components/tutorial/ChordPositioning.tsx
- src/components/tutorial/Instrumental.tsx
- src/components/tutorial/Playground.tsx
Adding the ability to insert tabs into lyrics. Tabs facilitate a bigger whitespace to anchor chords to.
> Adding Tabs for instrumental sections

- .github/workflows/docker-image.yml
> Deploy gke

- src/components/play/DisplaySettings.tsx
- src/components/play/Play.tsx
- src/components/play/PlayBlock.tsx
- src/components/play/PlayContent.tsx
- src/components/play/PlayMenu.tsx
Allow changing some formatting in the Play view - e.g. columns, font size
> Play settings

- src/App.tsx
- src/components/display/PageTitle.ts
- src/components/edit/ChordPaper.tsx
- src/components/play/Play.tsx
Using helmet templates to do the page titles
> Better way of doing page titles

- package.json
- src/App.tsx
- src/components/edit/ChordPaper.tsx
- src/components/play/Play.tsx
- src/test/chords.test.tsx
- src/test/common.tsx
- yarn.lock
This is causing a warning: https://github.com/nfl/react-helmet/issues/426
Using an apparently better drop in replacement of react-helmet-async
> Replace react-helmet with react-helmet-async

- src/components/WithSongContext.tsx
Auto save wasn't working because song context HOC neglected to pass on the song update notification - adding that back in.
> Fix auto save not working

- src/components/Tutorial.tsx
- src/components/tutorial/AddLine.tsx
- src/components/tutorial/Instrumental.tsx
- src/components/tutorial/Labels.tsx
- src/components/tutorial/PasteLyrics.tsx
- src/components/tutorial/PlayMode.tsx
- src/components/tutorial/RemoveLine.tsx
Tutorials for label and play mode
> Adding some missing tutorials

- package.json
Hooking it all up by adding a reachable backend url
> Adding prod backend URL

- src/components/user/Login.tsx
Putting it in the header instead of the post body to support https://github.com/veedubyou/chord-paper-be/pull/17
> Update login to add auth token in header

- src/common/ChordModel/ChordBlock.ts
Migration of local files complete - deserialization will only take lyric objects for lyrics and not strings now.
> Remove dual path for lyric deserialization

- package.json
- src/components/tutorial/CopyAndPaste.tsx
- yarn.lock
update dependencies due to vulnerability
> Node forge vulnerability

- src/components/edit/lyric_input/useKeyHandler.ts
- src/components/tutorial/Instrumental.tsx
- src/test/lyrics.test.tsx
- src/test/userEvent.ts
So Alt + Tab makes no sense because it can't work in windows - changing small tab to be Shift + Space
> Change Small Tab Key

- .gitignore
- src/components/user/Login.tsx
made a change on the backend to not accept a user ID in the login endpoint but forgot to reflect that in the front end
> idiot be idioting

- src/App.tsx
- src/common/paths.ts
- src/common/test/Whitespace.test.ts
- src/common/test/path.test.ts
- src/components/Demo.tsx
- src/components/SideMenu.tsx
- src/components/SongFetcher.tsx
- src/components/SongRouter.tsx
Refactoring path handling - before it was just strings handling and it was very difficult to maintain and juggle.
Trying out a collection of interconnected lightweight classes, each of which represent a particular scheme but can reach other other via class methods. Can be thought of as a graph or an FSM of some kind.
> Refactor paths

- src/common/ChordModel/ChordSong.ts
- src/components/edit/menu/cloudSave.ts
Some janky stuff too bootstrap song updating
> Update song functionality

- src/common/backend.ts
- src/components/SongFetcher.tsx
- src/components/edit/menu/cloudSave.ts
- src/components/user/Login.tsx
Centralizing all calls to the backend module instead of letting random callsites go yolo with the http client
> Consolidate all backend calls into one package

- src/common/ChordModel/ChordSong.ts
- src/common/backend.ts
- src/common/fetch.ts
- src/components/LoadSongDialog.tsx
- src/components/SideMenu.tsx
- src/components/SongFetcher.tsx
- src/components/display/ErrorImage.tsx
- src/components/edit/ChordPaper.tsx
- src/components/edit/menu/ChordPaperMenu.tsx
Dialog + fetching logic to fetch song listings for which the user is the owner of, and then loading it.
> Load songs

- src/components/LoadSongDialog.tsx
Another refactor to the song structure - help flatten and reuse common metadata since there was too much duplication.
> Refactor song structure

- src/components/LoadSongDialog.tsx
Mission success, stop rickrolling phil
> Stop rolling phil

- src/common/ChordModel/ChordSong.ts
Just making the migration of songs easier by providing a transitional type
> Relax Last Saved At in schema for migration

- src/common/ChordModel/ChordSong.ts
- src/common/ChordModel/test/ChordSong.test.ts
Make all fields mandatory as migration is over
> Remove optional fields from ChordSong

- package.json
- src/components/edit/menu/ChordPaperMenu.tsx
- yarn.lock
> Disable local JSON save and load by default, but can be enabled via Konami code

- src/common/backend/errors.ts
- src/common/backend/requests.ts
- src/components/LoadSongDialog.tsx
- src/components/SongFetcher.tsx
- src/components/WithCloud.tsx
- src/components/edit/menu/cloudSave.ts
- src/components/user/Login.tsx
Parse backend error codes and show a better and more actionable error message for every variety of error.
> Parse and show better error messages

- src/common/backend/errors.ts
Just updating some error messages
> Normalizing some error messages

- src/common/ChordModel/ChordSong.ts
- src/common/ChordModel/test/ChordSong.test.ts
- src/components/edit/menu/ChordPaperMenu.tsx
- src/components/edit/menu/cloudSave.ts
- src/components/edit/menu/save.ts
Adding the ability to fork - creating a copy of the song you're working on for divergent purposes (e.g. making it in a separate key, adding performance specific elements that are not available in the original transcription).
> Song forking functionality

- .github/workflows/docker-image.yml
- .github/workflows/pr-test.yml
- .github/workflows/publish-github-pages.yml
Custom runner can't be reached for some reason - swapping back to cloud runner until we can get it up.
> Swap back to cloud runner for now

- .github/workflows/docker-image.yml
- .github/workflows/publish-github-pages.yml
Effectively fixing the hacky https://github.com/veedubyou/chord-paper-fe/pull/156
Using advice from https://github.com/actions/toolkit/issues/641#issuecomment-730583850
> Github_env for env setting in workflows

- package.json
- src/common/URL.ts
- src/components/play/DisplaySettingsDialog.tsx
- src/components/play/Play.tsx
- src/components/play/PlayContent.tsx
- src/components/play/PlayMenu.tsx
- src/components/play/PlayerSettingsDialog.tsx
- src/components/play/SongPlayer.tsx
- yarn.lock
Adding an embedded player in the play view, so that the user can play along in an all-in-one place.
> Play player

- src/components/track_player/CompactPlayer.tsx
- src/components/track_player/TrackPlayer.tsx
- src/components/track_player/useMultiTrack.ts
Jump back button jumps back 5 seconds!
> implement jump back functionality

- src/components/track_player/CompactPlayer.tsx
I don't know why i tried to roll my own button group
> Using MUI's button group

- src/components/track_player/CompactPlayer.tsx
> Better compact player design

- src/components/PlayerTimeContext.tsx
- src/components/edit/ChordPaper.tsx
- src/components/edit/ControlledTextInput.tsx
- src/components/edit/TimeInput.tsx
- src/components/track_player/useMultiTrack.ts
Clicking the "play" button on the time label will insert the current time of the player:
> implemented current time button

- src/components/edit/WithSection.tsx
Whoops i broke the section label input - this fixes it but not sure if it's the best solution. Ship this for now until a better solution comes up.
> Fix broken section label input

- src/components/edit/WithSection.tsx
Slightly better fix - disable focus stealing only when editing the label
> Section fix #2

- src/components/edit/ChordPaper.tsx
- src/components/play/Play.tsx
- src/components/track_player/BeginningIcon.tsx
- src/components/track_player/CompactPlayer.tsx
- src/components/track_player/ControlButton.tsx
- src/components/track_player/FullPlayer.tsx
- src/components/track_player/TrackPlayer.tsx
- src/components/track_player/useMultiTrack.ts
Adding skip buttons that go between different sections if they've been marked on the song
> Skipping between sections in the track player

- src/components/track_player/CompactPlayer.tsx
- src/components/track_player/FullPlayer.tsx
- src/components/track_player/SectionLabel.tsx
- src/components/track_player/TrackPlayer.tsx
- src/components/track_player/useMultiTrack.ts
Adding a label on the track player that changes as the song goes
> Section Labels for Track Player

- src/assets/songs/never_gonna_give_you_up_plastic_love.json
- src/common/ChordModel/ChordSong.ts
- src/common/ChordModel/test/ChordSong.test.ts
- src/components/edit/Header.tsx
This field is effectively replaced by tracks, so removing it and making the model and UI cleaner.
> Removing As Heard From

- src/components/track_player/FullPlayer.tsx
Accidentally disabled the controls, undoing
> Restoring controls on full player view

- src/components/track_player/FourStemControlPane.tsx
- src/components/track_player/FourStemTrackPlayer.tsx
- src/components/track_player/fourStemTypes.ts
The abstraction is trash rn but feature is too cool to not ship immediately
> 4stems: make each stem toggleable

- package.json
- src/common/fetch.ts
- src/components/track_player/internal_player/4stems/FourStemTrackPlayer.tsx
- yarn.lock
Adding actual progress bars and file size progress.
> Adding loading indicators for 4 stem view

- src/components/track_player/internal_player/single/SingleTrackPlayer.tsx
Accidentally left out this behaviour during refactoring - adding back in.
> Fix GDrive cache busting

- src/components/play/keyMap.ts
> Fix navigation keys not working

- src/components/track_player/internal_player/4stems/FourStemTrackPlayer.tsx
A bunch of specific things to make the progress bar behave more naturally.
> Improve progress bar aesthetics

- src/App.tsx
- src/components/GlobalKeyListener.tsx
- src/components/play/PlayContent.tsx
- src/components/track_player/FullPlayer.tsx
- src/components/track_player/JamStation.tsx
- src/components/track_player/MultiTrackPlayer.tsx
- src/components/track_player/TrackPlayer.tsx
- src/components/track_player/internal_player/4stems/FourStemTrackPlayer.tsx
- src/components/track_player/internal_player/4stems/LoadedFourStemTrackPlayer.tsx
- src/components/track_player/internal_player/ControlPane.tsx
- src/components/track_player/internal_player/single/SingleTrackPlayer.tsx
Added ability to respond to hotkeys in the player - if it's up, then it'll respond to hotkeys over anything else.
> Hotkeys for player

- src/components/track_player/MultiTrackPlayer.tsx
- src/components/track_player/TrackPlayer.tsx
- src/components/track_player/internal_player/4stems/FourStemTrackPlayer.tsx
- src/components/track_player/internal_player/4stems/LoadedFourStemTrackPlayer.tsx
- src/components/track_player/internal_player/ControlPane.tsx
- src/components/track_player/internal_player/single/SingleTrackPlayer.tsx
If the user switches to another track, make sure to pause the current one.
> Pause track when not current track

- src/components/track_player/internal_player/4stems/FourStemControlPane.tsx
- src/components/track_player/internal_player/4stems/LoadedFourStemTrackPlayer.tsx
- src/components/track_player/internal_player/useTimeControls.ts
Adding individual volume sliders for each stem, so that they can be played in different balances.
> Volume sliders for each stem

- src/components/track_player/JamStation.tsx
- src/components/track_player/MultiTrackPlayer.tsx
- src/components/track_player/TrackPlayer.tsx
- src/components/track_player/internal_player/4stems/FourStemTrackPlayer.tsx
- src/components/track_player/internal_player/4stems/LoadedFourStemTrackPlayer.tsx
- src/components/track_player/internal_player/ControlPane.tsx
- src/components/track_player/internal_player/single/SingleTrackPlayer.tsx
Pressing / will toggle the player being visible or hidden
> Add show/hide player hotkey

- src/components/track_player/MultiTrackPlayer.tsx
- src/components/track_player/TrackPlayer.tsx
- src/components/track_player/internal_player/4stems/LoadedFourStemTrackPlayer.tsx
A button to refresh the track - sometimes loading can be wonky due to network conditions or others, a refresh button should be handy here.
> Adding track refresh button

- src/common/ChordModel/tracks/StemTrack.ts
- src/common/ChordModel/tracks/Track.ts
- src/common/ChordModel/tracks/TrackList.ts
- src/components/track_player/TrackPlayer.tsx
- src/components/track_player/dialog/TrackListEditDialog.tsx
- src/components/track_player/internal_player/stem/StemTrackControlPane.tsx
Some boiler plate that adds support for a 5 stem track which includes piano
> adding support for 5 stem tracks

- src/components/WithCloud.tsx
The little cloud button causes a navigation when saving a new song - that is an expected navigation and we shouldn't prevent it.
> Fix - don't prevent navigation when uploading new song

- src/components/edit/ChordPaper.tsx
- src/components/play/Play.tsx
- src/components/track_player/JamStation.tsx
- src/components/track_player/MultiTrackPlayer.tsx
- src/components/track_player/TrackListProvider.tsx
- src/components/track_player/dialog/TrackListEditDialog.tsx
Add refresh button to tracklist edit dialog
> Refreshable tracklist

- src/components/track_player/internal_player/stem/LoadedStemTrackPlayer.tsx
The pitch shift approach worked in that it made the output smoother, but it also causes a lot of weird clicking artifacts. Switching back to GrainPlayer for to see how well it works.
> Switch back to GrainPlayer for speed adjustment

- src/components/GlobalKeyListener.tsx
- src/components/play/PlayContent.tsx
- src/components/track_player/JamStation.tsx
- src/components/track_player/internal_player/ControlPane.tsx
- src/components/track_player/internal_player/useTimeControls.ts
Worked out some more kinks:
-added the don't take over input context behaviour to the global handler instead
-made everything in capture phase, so it's the first to intercept the event
> Better shortcut experience #2

- src/components/play/DisplaySettingsDialog.tsx
- src/components/play/Play.tsx
Making the default scrolling mode column based as that seems to be a bit better of an experience.
> Play mode: default column scrolling

- src/components/track_player/MultiTrackPlayer.tsx
Center the loading spinner on the track player so it doesn't look so ridiculous
> Track Player: Center loading spinner

- src/components/display/LastSavedAt.tsx
- yarn.lock
Types were broken last update - upgrading the types and undoing the commented out code.
> Fix last saved at

- src/components/edit/Block.tsx
- src/components/edit/block-dnd/ChordTokenDroppable.tsx
- src/components/edit/block-dnd/ChordlessTokenDroppable.tsx
- src/components/edit/block-dnd/DraggableChordSymbol.tsx
- src/components/edit/block-dnd/common.ts
- src/components/edit/block-dnd/useChordDrop.ts
Some refactoring - pull out the useDrop hook, simplifying and removing some types, etc.
> Refactoring DND

- package.json
Stuttering happening in the player - enabling this for investigation.
> Temp: Making production build profileable

- package.json
Reverts veedubyou/chord-paper-fe#253
> Revert "Temp: Making production build profileable"

- src/components/track_player/internal_player/reactPlayerProps.ts
Normally I don't care about Chrome but this seems an easy enough fix
> Fix player height in Chrome

- src/common/PlainFn.ts
- src/components/GlobalKeyListener.tsx
- src/components/Tutorial.tsx
- src/components/edit/InteractionContext.ts
- src/components/track_player/dialog/TrackListEditDialog.tsx
- src/components/track_player/internal_player/ControlPane.tsx
- src/components/track_player/internal_player/usePlayerControls.ts
- src/components/tutorial/AddChord.tsx
- src/components/tutorial/AddLine.tsx
- src/components/tutorial/ChordPositioning.tsx
- src/components/tutorial/CopyAndPaste.tsx
- src/components/tutorial/DragAndDropChord.tsx
- src/components/tutorial/EditChord.tsx
- src/components/tutorial/EditLyrics.tsx
- src/components/tutorial/Instrumental.tsx
- src/components/tutorial/MergeLine.tsx
- src/components/tutorial/PlayMode.tsx
- src/components/tutorial/RemoveChord.tsx
- src/components/tutorial/RemoveLine.tsx
- src/components/tutorial/RemoveMultipleLines.tsx
- src/components/tutorial/Saving.tsx
- src/components/tutorial/SplitLine.tsx
- src/components/tutorial/TimeLabels.tsx
- src/components/tutorial/TrackPlayer.tsx
Adding 3 more tutorials: track player, time labels, and batch line delete.
> Add more tutorials

- src/components/LoadSongDialog.tsx
- src/components/track_player/internal_player/ControlPane.tsx
- src/components/track_player/internal_player/TransposeControl.tsx
- src/components/track_player/internal_player/stem/StemTrackControlPane.tsx
Some strict mode things - adding keys to lists.
> Fix list key strict mode warnings

- .github/workflows/docker-image.yml
> Fix k8s deploy fail

- src/components/edit/BatchDelete.ts
- src/components/edit/ChordPaperBody.tsx
- src/components/edit/Undo.ts
- src/components/reducer/reducer.ts
Undo/Redo again, except preserving last saved at.
> Undo-Redo v2

- src/components/reducer/reducer.ts
Oops, forgot to include this change. Quick follow up instead of cleaner git practices.
> Undo/Redo: Fix last saved at

- src/components/guitar/FretSelector.tsx
- src/components/guitar/GuitarDemo.tsx
- src/components/guitar/MenuSelectableScaleChart.tsx
- src/components/guitar/ScaleChart.tsx
- src/components/guitar/ScaleSelection.tsx
Adding menus to each scale chart so that each can specify their own chart labels and starting frets
> Allow custom labels and starting fret for each scale chart 

- src/components/about/About.tsx
Adding credits to the about page for people who worked on this project.
> Adding credits

- src/common/ChordModel/tracks/SplitStemRequest.ts
- src/components/track_player/LoadingTrackView.tsx
Together with https://github.com/veedubyou/chord-paper-be-workers/pull/24 and https://github.com/veedubyou/chord-paper-be/pull/63
Shows job progress and current status message for the job.
> Show Job progress in progress bar

- src/components/track_player/LoadingSplitStemTrackView.tsx
- src/components/track_player/TrackPlayer.tsx
- src/components/track_player/providers/useTracklistFetch.ts
A couple quick follow ups - mainly reducing the debounce threshold to make the refresh feel more responsive.
> Small auto refresh adjustments

- src/components/play/scroll/PlaySection.tsx
- src/components/play/scroll/ScrollPlayContent.tsx
Adding a scroll up navigation (e.g. arrow up, page up, backspace, etc).
This scroll goes up to the previous section head.
> Scroll view - navigate backwards/up

- src/components/SongFetcher.tsx
Updating the modal background colour for the full screen load. Making it a bit darker so the dimming effect is more obvious.
> Update loading background colour

- src/components/edit/HighlightChordLyricStyle.ts
Just adding some corners on highlighted spaces because I found the rectangular corners too jarring.
> Rounded corners for highlighted spacing

- src/components/track_player/internal_player/usePlayerControls.ts
A super rough AB loop implementation.
Far from the finished thing but wanted to get a feel of how it works in real workflows.
Right now doing a CTRL/CMD+A with the player open will set or unset the AB loop to start from the current position. The AB loop will only last 5 seconds.
A UI for setting the loop will follow (along with a more customizable loop), but since it will displace other controls, a redesign of the controls will be needed.
> AB Loop v0

- public/index.html
> added analytics

- .gitignore
- package.json
- tsconfig.json
- yarn.lock
On a path to upgrade React and Material UI.
Nothing seemed to break just by doing this quite surprisingly.
> Upgrade to React 17

- public/index.html
change umami.js to randomstring.js
change subdomain of analytics site
> Init analytics

- src/components/edit/menu/ChordPaperMenu.tsx
Changing up some icons on the edit menu so that it's a bit more intuitive
Play mode: play arrow -> piano
Transpose: up down arrows -> flat sharp
> Change up menu icons

- src/components/icons/BIcon.tsx
- src/components/track_player/internal_player/ABLoop.ts
- src/components/track_player/internal_player/ControlButton.tsx
- src/components/track_player/internal_player/advanced_controls/ABLoopControl.tsx
- src/components/track_player/internal_player/usePlayerControls.ts
Adding the B button to the A/B loop UI. Taking out the A+5 second default for now, but looking to add it back in soon.
> A/B loop - B button

- src/components/icons/BIcon.tsx
- src/components/icons/Plus5Icon.tsx
- src/components/icons/makeTextIcon.tsx
- src/components/track_player/internal_player/ABLoop.ts
- src/components/track_player/internal_player/ControlButton.tsx
- src/components/track_player/internal_player/advanced_controls/ABLoopControl.tsx
- src/components/track_player/internal_player/usePlayerControls.ts
Adding a default loop button that loops 5 seconds from point A. Activating it hides the B button since the end point is set.
Turning the ABLoop into a class with immutable record so that I don't vomit related functionality all over the code base like an idiot (i.e. consolidating cohesion by grouping related functionality).
> AB loop: Default loop button

- src/components/edit/ChordPaperBody.tsx
- src/components/edit/LineWithSectionHighlight.tsx
Adding some rounded corners to the sections so they don't look as sad.
> Rounded corners for highlighted sections

- src/components/play/Play.tsx
Making scroll view the default play mode - it's seeming like the better experience than page mode.
> Play mode default is scroll view

- src/components/play/page/PagePlayContent.tsx
Adding section highlighted lines to the page view. It can end up splitting over pages but still looks pretty good.
> Add section highlighting to page view

- src/components/display/LineWithSectionHighlight.tsx
- src/components/edit/Line.tsx
- src/components/edit/NewLine.tsx
- src/components/play/scroll/ColourBorderBox.tsx
- src/components/play/scroll/ScrollPlayContent.tsx
- src/components/play/scroll/ScrollablePlayLine.tsx
- src/components/play/scroll/colourBorderContext.tsx
There's too many concepts in here that are called highlight and it makes the code a bit confusing so I'm renaming some of them. More apt design-y words will probably help here but until I get the right vocabulary inspiration this is an improvement still.
> Rename some highlight things

- src/components/edit/menu/TransposeMenu.tsx
- src/components/edit/menu/cloudSave.tsx
- src/components/reducer/reducer.ts
Adding a new ability to fork -> transpose at the same time, as this is a common pattern to preserve the song in the original key and make a copy in the transposed key.
> Allow transposing as a new copy of the song

- package.json
- src/common/ChordModel/ChordSong.ts
- src/components/LoadSongDialog.tsx
- src/components/display/KeyInfo.tsx
- src/components/edit/Header.tsx
- yarn.lock
Saving the from/to key after a transposition into the song. This can help pave some nice capabilities forwards like auto transposing for the track player.
> Save key transposition data

- src/common/backend/errors.ts
- src/common/backend/requests.ts
- src/common/fetch.ts
- src/components/LoadSongDialog.tsx
- src/components/SongFetcher.tsx
- src/components/display/ErrorImage.tsx
- src/components/display/OneTimeErrorNotification.tsx
- src/components/track_player/TrackPlayer.tsx
- src/components/track_player/internal_player/stem/StemTrackPlayer.tsx
- src/components/track_player/providers/TrackListProvider.tsx
- src/components/track_player/providers/useTrackFetch.ts
- src/components/track_player/providers/useTracklistFetch.ts
Improve how things look and feel when an error occurs.
Main changes:
-improve the error parsing code so that it's more comprehensive and gives better details
-adding types to the errors instead of unknown. even when it's unknown there's an assumed shape when I toss it in the parsing code, so it's best to surface those assumptions
-removing errorimage as a fallback render for most components. it's hilarious to see levi stomp eren's face in jankily inside a small component but it's getting old, so i'm saving it only for when the song itself can't load
> Improve the error experience

- .github/workflows/docker-image.yml
- install dependencies in workflow
- removed cleanup
> use new cluster runner

- src/components/edit/lyric_input/useKeyHandler.ts
Fixes https://github.com/veedubyou/chord-paper-fe/issues/366
The code to count the start offset is not quite right during a CTRL+Enter action. The code only considers the start offset with respect to the container, which is usually the text node. If there are tabs (rendered as spans), then the count will be wrong. This fix considers the tab spans as their own characters in the count of the start offset.
> Fix improper line splitting when tabs are present

- src/components/user/Login.tsx
Adding a Google form for requesting a Chord Paper account for those who don't have one.
> Add form request for no account users

- package.json
- src/App.tsx
- src/components/display/OneTimeMobileNotification.tsx
- src/components/user/Login.tsx
- yarn.lock
Adding a one time pop up dialog for mobile visitors warning them to not do it.
> Mobile warning

- src/components/track_player/internal_player/advanced_controls/TempoControl.tsx
Adding more fine tuned controls to tempo control....right click now == 1% up or down.
Would be nice to have a bpm control, but unclear how to design that nicely right now.
>  Add 1% changes to tempo control

- package.json
Pointing prod to my local computer until backend is restored
> Redirect backend until back up

- package.json
Reverts veedubyou/chord-paper-fe#396
> Revert "Redirect backend until back up"

- src/common/ChordModel/tracks/SplitStemRequest.ts
Changing the types ahead of time to setup for demucs support
> Setting up demucs

- src/components/track_player/dialog/SplitStemTrackRow.tsx
In the select box, the text was too long and overflowed 🤦 
Instead of finding an elegant solution I'm just gonna shorten it
> Overflowed Demucs fine tuned

- .github/workflows/workflow-tester.yml
Testing new arc-runner with a test workflow to see if it works in production - seems like I have to merge to master to get the workflow to appear in Actions menu
> added manual testing workflow

- src/components/track_player/internal_player/stem/LoadedStemTrackPlayer.tsx
Reverts veedubyou/chord-paper-fe#418
turns out it's not so good
> Revert "better tempo/pitch shifting"

- src/components/track_player/internal_player/stem/LoadedStemTrackPlayer.tsx
Give a hacky way to control grain size and overlap while i experiment with the values.
use ?g=val&o=val to control this
> dynamic grain/overlap config

- package.json
- public/index.html
- src/components/user/Login.tsx
- src/components/user/userContext.ts
- src/google.d.ts
- yarn.lock
Reverts veedubyou/chord-paper-fe#422
> Revert "update google auth"

- package.json
- public/index.html
- src/components/user/Login.tsx
- src/components/user/userContext.ts
- src/google.d.ts
- yarn.lock
Reverts veedubyou/chord-paper-fe#425
> Revert "Revert "update google auth""

- package.json
- public/index.html
- src/components/user/Login.tsx
- src/google.d.ts
- yarn.lock
Reverts veedubyou/chord-paper-fe#424
> Revert "Revert "feat: google one tap""
