veedubyou/chord-paper-fe

.github/workflows/docker-image.yml

dockerhub image `pw1124/chord:latest` now references the newest version (i.e. the latest push on master branch)

added push to latest image

---

package.json

Use a relative build path instead of an absolute one - there were some issues with mixed http/https, and it's better to just let relative paths worry about the protocol.

Make build path relative for Github Pages

---

src/components/EditableLine.tsx

Bug: typing in the middle of lyrics would cause the cursor to go to the end of the line, making for a frustrating typing experience.
The issue is something to do with the dynamically generated HOC styled TextFields that may change depending on the props - somehow this causes focus to leave the text box and the autofocus props would refocus, and therefore cause the cursor to jump to the end.
Instead of dealing with HOC styles I just opted to change the font size deep in the input ref - not the best solution but it minimizes the moving parts and I was already changing styles in the inenr input.

Bug: Typing in middle of line would jump cursor to end of line

---

src/common/ChordModel/ChordLinePatcher.ts
src/common/ChordModel/test/ChordLinePatcher.test.ts

When patching a line of lyrics, a bug occurs where it's possible to end up with two consecutive blocks with no chords. this just patches that such that in those cases, the lyrics are just merged into the same block.

Bug: Don't allow two consecutive blocks with no chords

---

src/components/Block.tsx
src/components/TextInput.tsx
src/test/chords.test.tsx

Make editing a chord a tooltip hover button for now, until a better design is implemented.

Change chord edit/insert to hover button instead of clicking on word

---

src/components/Block.tsx
src/components/ChordSymbol.tsx
src/components/LyricToken.tsx
src/components/Outline.ts
src/test/chords.test.tsx

Simplifying the code further: All lyric tokens now have an invisible target by which hovering or clicking triggers outlining and chord editing respectively. The special handling for the first token now is whether or not it trips a highlight flag.

Add invisible target for first lyric token

---

src/components/edit/Block.tsx
src/components/edit/ChordPaperBody.tsx
src/components/edit/InteractionContext.ts
src/components/edit/Line.tsx
src/components/edit/TextInput.tsx

Making the app have only one interaction at a time through disabling pointer events. If any child components start an edit, it flags the interaction state and it would prevent starting any other interactions until the current one is finished.
This was the cause of some user confusion when chord boxes were highlightable while the lyrics were being edited.

Only one interaction at a time

---

src/components/display/ChordSymbol.tsx
src/components/display/Lyric.tsx
src/components/edit/Block.tsx
src/components/edit/Line.tsx
src/components/edit/TextInput.tsx
src/test/chords.test.tsx
src/test/lyrics.test.tsx

Changing all text inputs to be contenteditable, with nerfed commands, as text inputs. This allows more control over the styling of the text and lets the editing text more closely resemble the displayed text.

Use ContentEditable instead of input field

---

src/common/BrowserSave.ts
src/common/ChordModel/ChordBlock.ts
src/common/ChordModel/ChordLine.ts
src/common/ChordModel/ChordSong.ts
src/common/ChordModel/Collection.ts
src/common/ChordModel/test/ChordBlock.test.ts
src/common/ChordModel/test/ChordLine.test.ts
src/common/ChordModel/test/ChordSong.test.ts
src/components/Tutorial.tsx
src/components/display/ChordSymbol.tsx
src/components/edit/ChordEditLine.tsx
src/components/edit/ChordPaperBody.tsx
src/components/edit/ChordPaperMenu.tsx
src/components/edit/CopyAndPaste.ts
src/components/edit/Line.tsx
src/components/edit/TextInput.tsx
src/components/tutorial/CopyAndPaste.tsx
src/test/common.tsx
src/test/lyrics.test.tsx
src/test/paste.test.tsx

Allow copying and pasting contiguous sections of lines. This works by adjusting selection ranges, and checking whether elements with specific data attributes (in this case, the line ID) exists inside the selection, and pulling those lines from the model.
No tests because JSDom's selection doesn't quite work yet.

Copy and Paste

---

src/components/edit/ChordPaperBody.tsx
src/components/edit/TextInput.tsx

A couple issues with single line plain text pasting that wasn't great:
1) copying while in lyric edit mode bubbled to line copy behaviour - it should be more like free form text copying. now the body blocks attaching the copy handler if an interaction is in progress
2) pasting a single line of plain text into the lyric box caused some weird formatting issues due to the contenteditable being copy/pasted. overriding the default behaviour by using existing text insertion methods.

Single Line Plain Text Copy bugs

---

src/App.tsx

A rogue semicolon leaked into the document

random ass semicolon

---

src/components/Tutorial.tsx
src/components/edit/ChordPaperBody.tsx
src/components/edit/Line.tsx
src/components/edit/TextInput.tsx
src/components/edit/WithLyricInput.tsx
src/components/tutorial/SplitLine.tsx

Not true line splitting, only lyric splitting.
CTRL/CMD + Enter will split lyrics at the cursor, and push the latter half to a new line. Chords however will not follow and it will simply get moved around as if it was edited...this is a refinement that I may revisit in the future (to move chords when split). The current issue also stands when a lyric paste happens mid line.

Line splitting

---

src/components/play/PlayContent.tsx

Based on feedback from Jeff - try disabling smooth scrolling to make the transition instantaneous.

Play mode: disable smooth scrolling

---

src/components/user/Login.tsx

Right now, refreshing will log the user out even though they were logged in. This is logic that must be handled manually, but more importantly is that gapi.auth2.init returning an auth client is a lie - it firstly returns an uninitialized set of data, but it will return more real data if chained as a promise. wtf.

Retain login on refresh

---

src/components/user/Login.tsx

Right now, if the client is disconnected from the internet, script loading gapi will fail but Login.tsx will continue to try to function as if gapi is there due to the typing, and will cause the whole app to crash - super inconvenient for offline development.. This guards against that code from continuing if gapi is not loaded.

Guard login code depending on gapi loading

---

src/common/ChordModel/test/Lyric.test.ts
src/components/edit/lyric_input/SelectionUtils.ts
src/components/edit/lyric_input/useKeyHandler.ts
src/components/lyrics/Tab.tsx
src/components/tutorial/AddLine.tsx
src/components/tutorial/ChordPositioning.tsx
src/components/tutorial/Instrumental.tsx
src/components/tutorial/Labels.tsx
src/components/tutorial/PasteLyrics.tsx
src/components/tutorial/RemoveLine.tsx
src/test/chords.test.tsx
src/test/lyrics.test.tsx
src/test/userEvent.ts

Brief usability tests show that medium (size 2) tabs are the most frequently desired size, so mapping default tab to that and turning size 1/small to ALT/OPTION + tab, also adding in large tab as SHIFT + tab.

adding large tab and remapping keys

---

src/common/ChordModel/ChordLinePatcher.ts
src/common/ChordModel/test/ChordLinePatcher.test.ts
src/test/lyrics.test.tsx

When blocks are orphaned due to not having any lyrics, fill the empty block with a small tab instead of a space - when blocks are just spaces they're super painful to deal with and having something chonkier like a tab makes the lyric editing process a lot more ergonomic.

Patch orphaned blocks with tabs instead of spaces

---

src/assets/songs/never_gonna_give_you_up_plastic_love.json
src/common/ChordModel/test/ChordLinePatcher.test.ts
src/common/ChordModel/test/Lyric.test.ts
src/components/lyrics/Tab.tsx
src/components/tutorial/AddLine.tsx
src/components/tutorial/ChordPositioning.tsx
src/components/tutorial/Instrumental.tsx
src/components/tutorial/Labels.tsx
src/components/tutorial/PasteLyrics.tsx
src/components/tutorial/RemoveLine.tsx
src/test/chords.test.tsx
src/test/lyrics.test.tsx

Turns out having <stuff> tags were a bad idea - specifically for the lyric differ which can only treat each character separately, and therefore there are cases where the diff can result in a broken tag despite normal user input.
Switching small, medium, large tabs to U+E100, U+E200, and U+E400 (reserved private chars) respectively, which can only be processed atomically.

Change serialized tabs to private unicode chars

---

src/components/SideMenu.tsx

Login button should stay at the bottom, but absolute positioning isn't the way to do it since the component can exceed 100% of the height. When the tutorial expands, the Login button gets stuck in the middle of the tutorial list. Solution here is to add an intermediate filler element of variable height, but will grow to fill the parent container.

Restyling Login

---

src/components/play/PlayContent.tsx

Was bad design decision, reverting. Not seeing the animation disorients the user from keeping track of where is where.

Revert "Play mode: disable smooth scrolling"

---

src/common/ChordModel/ChordSong.ts

During cloning, the lastSavedAt wasn't copied over because errors of omission are difficult to catch. Using the spread operator to make sure everything is captured.

LastSavedAt gets discarded upon any change to the song

---

src/components/display/LastSavedAt.tsx

Decided that relative time is still better if it's within a day, other than that just show the date but omit the seconds - that seems pointless.

Minor reformatting of time display

---

src/components/SideMenu.tsx
src/components/edit/menu/ChordPaperMenu.tsx
src/components/edit/menu/cloudSave.ts

Some menu items just don't work unless the user is signed in, so hide them unless they're signed in to prevent confusion.

Hide menus that the user can't use unless signed in

---

src/common/ChordModel/ChordSong.ts
src/components/LoadSongDialog.tsx
src/components/WithCloud.tsx
src/components/edit/menu/cloudSave.ts
src/components/user/Login.tsx
src/components/user/userContext.ts

When the user logs in, we retain the auth/id token for the purposes of authorizing and authenticating, but the token's only valid for 1 hour. If the user works for over an hour on the app, then requests will start failing.

Refresh Google auth token when expired

---

.github/workflows/docker-image.yml
.github/workflows/publish-github-pages.yml

There's a vulnerability that prevents the use of set-env - the right way to do this is via something called environment files but the biggest risk would just be the version number being hijacked - a fairly minor thing so override for now until there's bandwidth to fix.

adding env that allows set-env

---

src/components/edit/menu/ChordPaperMenu.tsx
src/components/play/DisplaySettingsDialog.tsx
src/components/play/Play.tsx
src/components/play/PlayContent.tsx
src/components/play/PlayLine.tsx

In play mode, navigation to the last page can be confusing if there aren't enough columns to fill the page, and the scroll will be less than one page width.
e.g., Suppose in a 3 column layout, there's enough content for 4 columns - a, b, c, d
the first page will be `a | b | c`
but the scroll to the second page will look like `b | c | d`
This is particularly bad if the song is repetitive and the user expects the left side to be where to start reading again, only to read content they already played past.
This change pads the end with enough empty columns so that the next page flows immediately after:
e.g. `a | b | c`, then `d | [empty] | [empty]`

Fill empty columns in play mode

---

src/components/edit/menu/ChordPaperMenu.tsx
src/components/play/PlayMenu.tsx

-Move menu button in edit mode to the top right
-Move both menu + play menu buttons down a nudge
-Change icons from + and hamburger to vertical triple dots to not collide with left side hamburger

Consolidate menu buttons

---

src/components/edit/Block.tsx
src/components/edit/ChordDroppable.tsx
src/components/edit/ChordPaperBody.tsx
src/components/edit/DragAndDrop.tsx
src/components/tutorial/DragAndDropChord.tsx

Adding CMD/CTRL chord drag and drop as a copy action, so that users can keep reusing chord symbols.
Huge hacks were done here because of React DND being both rigid (which can be good) and unmaintained (which makes things impossible along with the rigidity).

Command/Ctrl Chord Drag and Drop

---

src/components/track_player/FullSizedPlayer.tsx
src/components/track_player/TrackPlayer.tsx
src/components/track_player/google_drive.ts

Problem: when using a Google Drive export link, Firefox (maybe also chrome, but who cares) will cache the series of redirects for the link, i.e.
hit export link -> 302
some intermediate links -> 302
some one time auth link -> 200
If the audio file is not completely loaded in the browser cache, Firefox will resume loading from the cached redirect, that is, the one time auth link, and end up at a 403.
This workaround adds a random cache buster (random ID parameter) so that the browser won't follow the cache and grab a new redirect link.

Fixing Google Drive cache problem

---

src/components/track_player/TrackListEditDialog.tsx
src/components/track_player/google_drive.ts

Adding a key handler in the URL field of the track edit pane to convert a GDrive view link to a GDrive export link.
The secret key is CTRL/CMD + g

GDrive secret conversion key combo

---

src/components/track_player/TrackPlayer.tsx

Don't load the player unless the user chooses to expand the player - this prevent unnecessary bandwidth usage for loading songs.

Lazy load track player

---

src/components/track_player/CompactPlayer.tsx
src/components/track_player/FullPlayer.tsx
src/components/track_player/MinimizedButton.tsx
src/components/track_player/TrackPlayer.tsx
src/components/track_player/common.tsx
src/components/track_player/useMultiTrack.ts

Adding the small sized compact player - this is the intended size that I expect most users to interact with since it is small and out of the way.
one issue: the time display is lagging on the order of 1 second or so

Implementing compact player

---

src/components/track_player/ControlButton.tsx

Problem: disabled buttons still had a bright colour instead of a greyed out one - turns out I was styling the icons and not the buttons themselves. Moved the colour styles to the button and the greyed colour hint is back.

Fix disabled button styles

---

src/components/track_player/ControlButton.tsx
src/components/track_player/ControlGroup.tsx
src/components/track_player/FullPlayer.tsx
src/components/track_player/useMultiTrack.ts

Problem: on rapid button clicks on the player, e.g. play then pause, or jump back then pause, etc, React Player runs into some sort of race condition where its behaviour becomes decoupled from its input props (specificially `playing`). This is an (unpleasant) workaround to fix it.

Bug: Player out of sync

---

src/components/edit/EditableTypography.tsx

Typescript didn't catch this - and now the placeholders don't show up

Bug: Broke editable typography placeholders

---

src/components/track_player/CompactPlayer.tsx
src/components/track_player/TrackPlayer.tsx
src/components/track_player/useMultiTrack.ts

Adding the forward buttons to the compact player.
I thought about keeping it more spartan, but the forward buttons aren't superfluous - they're important for helping navigate a song esp if the user goes too far back and doesn't want to wait 30 seconds to get back to where they were. I think having these buttons in this view will justify this view more.

More compact player buttons

---

src/components/SongRouter.tsx

Bug: refreshing a play view will redirect into the edit view
I don't fully comprehend, but seems like react router's <Redirect>'s from parameter doesn't actually do anything - it will just execute a redirect upon mounting. Wrapping this in a route seems to solve the problem.
before: /song/id/play -> <song fetching> -> <rendering react routes + redirect> -> <redirect to /song/id/edit>
now: /song/id/play -> <song fetching> -> <rendering react routes + redirect> -> does not redirect because the redirect is wrapped inside another route

change redirect into a route

---

src/components/track_player/FullPlayer.tsx
src/components/track_player/useMultiTrack.ts

Also adding the play/pause button in the full view, even though it's also provided by the embedded player. It's a bit jarring to go to 2 different places to navigate, although it does create some nonstreamlined experience by having 2 ways to play/pause.
Will provide an options dialog to disable embedded controls in the future.

Add Play Button in Full Track Player

---

src/components/play/PlayLine.tsx

Bug: the inline-block style causes chord lines to be placed on the same line if they're short enough. I can't remember why this was ever here in the first place - removing.

Bug: Fix Play Line rendering

---

src/components/edit/TextInput.tsx

In refactoring, props.classes had been neglected to be propagated down, this caused chord inputs to be super long as opposed to the specified width.

Bug: Fix Chord Input size

---

src/components/edit/ChordPaper.tsx
src/components/play/Play.tsx
src/components/track_player/TrackListProvider.tsx

Don't try to save the tracklist if the change is initiated by a non-owner. The backend should prevent this already, but it will cause an unpleasant user experience to get a ton of error messages. When a non-owner tries to change, just change the tracklist locally but do not persist to the cloud.

Prevent other users from trying to save the tracklist

---

src/components/track_player/FourStemTrackPlayer.tsx
src/components/track_player/dialog/TrackListEditDialog.tsx

Handle the error state if the fetch fails - show an error pane and a refresh button to retry.

Handle error in loading tracks

---

src/components/play/PlayContent.tsx

Moving the key handling to window scope instead of the element - sometimes after collapsing the player the focus doesn't return to the body so the view doesn't response to keys unless clicked on, which is a frustrating experience.
Making the entire window respond to keystrokes should hopefully make the experience smoother.

Play view: move key handling to global window scope

---

src/components/play/PlayContent.tsx
src/components/play/keyMap.ts

"Everything else scrolls forward" as a behaviour is too aggressive - this creates situations where even pressing the volume up button or CTRL + T for a new tab would cause scrolling.
Narrowing it down to the "general" set of keyboard buttons - had to specify each individually though which was not fun.

Play view: reduce scroll button set

---

src/components/track_player/internal_player/4stems/LoadedFourStemTrackPlayer.tsx

Mute needs to be set after the volume, since setting the volume can unmute the node.

Fix mute behaviour

---

src/components/track_player/internal_player/4stems/LoadedFourStemTrackPlayer.tsx

Special handling for when volume is 0 - seems like setting it to negative infinity manually doesn't turn the track off, so toggling the mute when volume reaches zero.

Fix: mute when volume goes to 0

---

src/components/track_player/JamStation.tsx
src/components/track_player/MultiTrackPlayer.tsx
src/components/track_player/TrackPlayer.tsx
src/components/track_player/internal_player/4stems/FourStemTrackPlayer.tsx
src/components/track_player/internal_player/4stems/LoadedFourStemTrackPlayer.tsx
src/components/track_player/internal_player/ControlPane.tsx
src/components/track_player/internal_player/PlayrateControl.tsx
src/components/track_player/internal_player/single/SingleTrackPlayer.tsx

Implemented adjustment of playback speed for the multi stem player. Also pushed the playrate state down to the individual player level - if playback time is not shared, then no real reason for playback speed to be shared.

Adjusting play speed for multi stem player

---

src/components/track_player/internal_player/4stems/LoadedFourStemTrackPlayer.tsx
src/components/track_player/internal_player/PlayrateControl.tsx

The grain player kind of sucks and causes a lot of jittery artifacts, going with the original approach of changing the speed, then running through a pitch shift to compensate for the change in frequency. This seems to give a more stable result.

Improve play speed change sound quality

---

src/common/paths.ts
src/components/WithCloud.tsx

Adding event handlers on navigation or window closing events if the user tries to navigate away while the song is unsaved - so that there's no surprise if they lose their changes.

Prompt user from navigating away if there are unsaved changes

---

src/components/play/PlayContent.tsx

Allow playcontent to only intercept the keystrokes that are aimed at the default "body" so that it doesn't steal keystrokes from other things, e.g. text fields.

Fix: playview intercept only default body keystrokes

---

src/components/play/DisplaySettingsDialog.tsx
src/components/play/Play.tsx
src/components/play/PlayContent.tsx

Adding an option to scroll one column at a time instead of one page at time - this requires the user to do more scrolling actions to get through the song but would allow a healthy amount of lookahead so that the next page isn't a surprise.

Play mode: scroll by column option

---

src/components/track_player/internal_player/stem/LoadedStemTrackPlayer.tsx
src/components/track_player/internal_player/stem/StemTrackPlayer.tsx

Issue is because we've moved over to passing in the button specifications along with the audio buffers, the input array is created fresh on every render, so any props that trigger a rerender will cause the innards of the loaded player to change and replay the song from the beginning.
Fix is to rewrite it in a way that preserves referential equality by shoving the entire input into state as opposed to merging it right before, which creates a new object. Questionable fix...

Fix: player resetting when hidden

---

src/components/track_player/internal_player/single/SingleTrackPlayer.tsx
src/components/track_player/internal_player/stem/LoadedStemTrackPlayer.tsx
src/components/track_player/internal_player/useTimeControls.ts

Auto time insertion for section labels weren't working because the get time fn was being overridden by other players - this didn't happen before but it was probably just serendipity by the ordering of rendering. Now that it's changed, it's obvious that it needs to be guarded by focused - only the focused player should set the time context.

Fix: player time context for labels not working

---

src/components/play/PlayContent.tsx
src/components/track_player/internal_player/ControlPane.tsx
src/components/track_player/internal_player/useTimeControls.ts

The hotkeys right now just sometimes work sporadically, depending on the focused element. It doesn't fire all the time because it would disable any sort of keyboard input. Improvement here is to just fire all the time, unless the event is targetted towards an input / contenteditable context.

Improve hotkey experience

---

src/common/ChordModel/ChordBlock.ts
src/common/ChordModel/ChordLine.ts
src/common/ChordModel/ChordSong.ts
src/common/ChordModel/test/ChordLine.test.ts
src/components/edit/ChordPaperBody.tsx
src/components/edit/Line.tsx
src/components/edit/WithLyricInput.tsx
src/components/edit/lyric_input/LyricInput.tsx
src/components/edit/lyric_input/useKeyHandler.ts

CTRL/CMD + enter to split the line at the cursor - this already existed, but was incorrectly implemented out of lack of usecase and effort - it would just split the lyrics and leave the chords behind on the first line.
This implementation actually cuts the line in half and splits it - it was a recurring painpoint when the user would need to divide up the line differently after transcribing harmony had started

Split line for reals

---

src/components/GlobalKeyListener.tsx
src/components/track_player/internal_player/reactPlayerProps.ts
src/components/track_player/internal_player/single/SingleTrackPlayer.tsx
src/components/track_player/internal_player/stem/LoadedStemTrackPlayer.tsx

Some confusing coupling going on here...
Issue: pressing space to pause on the keyboard doesn't work as it should sometimes if the last focus was still on the audio element - it would pause and then unpause because the key handlers and audio element would both toggle the play state.
Fix here is to prevent default on all keyups for the react player. Might be a bit aggressive, but we're already intercepting the keys on keydown.

Fix: Keyboard pause doesn't work sometimes

---

src/components/track_player/internal_player/ControlButton.tsx
src/components/track_player/internal_player/ControlGroup.tsx
src/components/track_player/internal_player/ControlPane.tsx
src/components/track_player/internal_player/TransposeControl.tsx
src/components/track_player/internal_player/reactPlayerProps.ts
src/components/track_player/internal_player/single/SingleTrackPlayer.tsx
src/components/track_player/internal_player/stem/LoadedStemTrackPlayer.tsx
src/components/track_player/internal_player/usePlayerControls.ts

Adding key transposition to the audio portion of the player. This only works for the stem player since that's where we have control over the audio transformations.
Drums are exempt from this as a special case - drums transposed do not sound good.

Track Player: Transpose keys

---

src/components/edit/Line.tsx

When lyrics extend past one line, the current behaviour is to display it on multiple lines. This is confusing, especially when editing.
Changing the behaviour to just clip the lyrics instead - since this is not the intended usage (for lyrics to overflow), it's just a temporary state until the user fixes it.

Clip lyrics instead of multi line in overflow

---

src/components/track_player/MultiTrackPlayer.tsx
src/components/track_player/internal_player/ControlGroup.tsx
src/components/track_player/internal_player/ControlPane.tsx
src/components/track_player/internal_player/SectionLabel.tsx
src/components/track_player/internal_player/reactPlayerProps.ts

Right now, the track player just expands and contracts with their content size, which is primarily driven by the control pane. This results in a super confusing experience where your buttons and seek bar moves around as the song goes between sections (as section labels change the width of the player).
Fix here is to restrict width sizes to be at most 50vw, and at least the width of the transport controls (and if the window size is too small, then the width is the width of transport controls).
To maintain a sane control pane behaviour, the control pane now bumps off each unit (e.g. tempo control, pitch control, then section label) as space runs out.

Fix: Track player width and controls change location when section label changes

---

src/common/ChordModel/ChordLine.ts
src/components/edit/CopyAndPaste.ts

When copying and pasting lines, section labels aren't really what the user (i.e. me) is looking for, it's mostly the chord/lyric content. It's usually nontransferable, and in the case of section labels with time, it's almost never transferable.

Omit section data when copying lines

---

src/components/track_player/internal_player/ControlPane.tsx

Move the transpose control to the right side, so that it's the first to disappear - the tempo control is more likely to be used so it should disappear after the transpose, not before.

Usability: swap transpose and speed controls

---

src/components/useCloud.tsx

Reordering this check - isOnline performs a network ping, but we don't actually need to do it unless the state is dirty.

Delay checking isOnline

---

src/components/track_player/internal_player/ControlButton.tsx

Key strokes to play/pause (spacebar) is also causing a press on the last transport button that was focused - doing a preventdefault there so that no surprises happen.

Fix: Keyboard shortcuts also invoke transport control 

---

src/components/edit/DragAndDrop.tsx
src/components/tutorial/DragAndDropChord.tsx

Support Option/Alt also for the copy chord drop. When holding option on macos at least, the little copy plus icon will be adorned, so we should at least follow the visual cue.

Allow option/alt key to result in copy drop

---

src/components/track_player/internal_player/ControlGroup.tsx
src/components/track_player/internal_player/ControlPane.tsx

Making this thing look better
-removing the edge dividers on the transport controls and the playrate controls
-pushing the playrate + transposition controls all the way to the right. if given enough space, the playrate controls used to wander to the middle

ControlPane styling improvements

---

src/components/edit/Line.tsx

Found a callback to use instead of explicit coordination for removing the line from the tree.

Remove timeout for line removal

---

src/components/edit/BatchDelete.ts
src/components/edit/ChordPaperBody.tsx
src/components/edit/Undo.ts

Right now, keys for the body only work when it's focused on the paper body, but sometimes the user is focused outside and still wants to undo. Moving it to global seems more intuitive as a user interaction.

Move body key handlers to global

---

src/components/edit/Token.tsx

The chord input box gets cut off on Windows. Moving it down slightly.

Improve box styling on Windows

---

src/components/play/PlayContent.tsx

On Windows, for some reason play mode causes scrollbars to render. At 100vh, it shouldn't cause scrollbars but nonetheless it does.
A better fix would be to fix the CSS on Windows such that it doesn't cause scrollbars. However, there is a firefox CSS style that can hide the scrollbars so using that for now.

Play mode: Hide scrollbars

---

src/common/ChordModel/tracks/SplitStemRequest.ts
src/components/track_player/LoadingTrackView.tsx
src/components/track_player/TrackPlayer.tsx
src/components/track_player/dialog/TrackListEditDialog.tsx

Together with https://github.com/veedubyou/chord-paper-be/pull/62 and https://github.com/veedubyou/chord-paper-be-workers/pull/23
This surfaces any errors that the async audio processing jobs encounter and shows them to the user.
Exact progress reporting is coming soon.

Add error status view

---

package.json
src/App.tsx
src/components/play/PlayContent.tsx
yarn.lock

Issue: 
In Play mode, scrolling behaviour was unaligned to pages on Windows. This was an unintended side effect from https://github.com/veedubyou/chord-paper-fe/pull/275 . Clearly that wasn't the right fix due to it being a bandaid. It also only works in Firefox, not Chrome.
The desired state is to have no vertical scrollbars (although horizontal scrollbars is expected due to songs being usually longer than one screen) - then the scroll distance will not need to worry about scrollbar widths at all.
Play mode content has height set to 100vh, but with a horizontal scrollbar, the content is hidden by the horizontal scrollbar and introduces a vertical scrollbar just to scroll the little bit occluded by the horizontal scrollbar.
This is not an issue on MacOS because the scrollbar is basically …

Fix misaligned scrolling in play mode on Windows

---

src/components/Tutorial.tsx
src/components/tutorial/AddChord.tsx
src/components/tutorial/AddLine.tsx
src/components/tutorial/ChordPositioning.tsx
src/components/tutorial/CopyAndPaste.tsx
src/components/tutorial/DragAndDropChord.tsx
src/components/tutorial/EditChord.tsx
src/components/tutorial/EditLyrics.tsx
src/components/tutorial/Instrumental.tsx
src/components/tutorial/Labels.tsx
src/components/tutorial/Login.tsx
src/components/tutorial/MergeLine.tsx
src/components/tutorial/PasteLyrics.tsx
src/components/tutorial/PlayMode.tsx
src/components/tutorial/RemoveChord.tsx
src/components/tutorial/RemoveLine.tsx
src/components/tutorial/RemoveMultipleLines.tsx
src/components/tutorial/SplitLine.tsx
src/components/tutorial/Start.tsx
src/components/tutorial/TimeLabels.tsx
src/components/tutorial/TrackPlayer.tsx
src/components/tutorial/TutorialComponent.ts
src/components/user/Login.tsx

Cleaning up some stuff from the last PR: the links to tutorial pages were hard linked.
Adding the ability to resolve a tutorial's link by referencing that tutorial's component.

Tutorial page route utility

---

src/components/play/PlayContent.tsx

Adding some throttling to the scroll behaviour in play mode - users (i.e. me) can accidentally double tap a scroll which is usually not what's desired, and then have to go back during a playthrough. This change prevents that by only allowing one scroll event in a time interval.
The time interval value might need to be fine tuned after more testing.

Add throttling to scrolling in play mode

---

src/components/SongFetcher.tsx

Making the page load spinner less ugly by centering is vertically, and adding a modal effect so the background also blurs.
Before:
After:

Centering the page load spinner

---

package.json

In order to silence dependabot alerts that aren't real.

Move react-scripts into dev dependencies

---

src/App.tsx
src/common/paths.ts
src/common/test/path.test.ts
src/components/SongRouter.tsx
src/components/edit/menu/cloudSave.tsx
src/components/play/Play.tsx
src/components/useCloud.tsx

Giving Play scroll view and Play page view a URL path instead of toggling on component state, this allows the user to refresh the page without switching views unexpectedly.

Assigning a URL path to Play scroll + page views

---

src/App.tsx
src/common/paths.ts
src/components/LoadSongDialog.tsx
src/components/SideMenu.tsx
src/components/SongFetcher.tsx
src/components/SongRouter.tsx
src/components/Tutorial.tsx
src/components/about/About.tsx
src/components/display/CenteredLayout.tsx
src/components/display/CenteredLayoutWithMenu.tsx
src/components/edit/ChordPaper.tsx
src/components/edit/menu/cloudSave.tsx
src/components/play/Play.tsx
src/components/user/userContext.ts
src/test/common.tsx

A biggish refactor for how to insert page wide layouts on the component tree.
The motivation for this change was due to a change that happened some PRs ago where state and contexts were lost due to layout changes - layout changes shouldn't affect any functionality, yet if the layout changes they could cause a dismount of components below it and cause a functional difference.
The change: initially App.tsx held all the dirtiness in determining who gets what sort of layout, but trying to push this responsibility a bit lower. Each major section now has a respective "screen" component, which sets up the page wide layout. This seems be in the component tree right below the routing, and there may be some opportunity there for combining them in the future.

refactored layout + routes

---

src/components/edit/Line.tsx

Change the icon for editing the section label to a bookmark. Maybe it'll be more intuitive, we'll see.

Switch section label edit icon to bookmark

---

src/components/play/scroll/ScrollPlayContent.tsx
src/components/play/scroll/ScrollablePlayLine.tsx

Implementing the scroll up functionality of the new scroll view. This is similar to scroll down, except it considers the entirety of the previous viewport (100vh up from current viewport) as the space for selecting a candidate for scrolling.
To be clear, the code looks at the hidden space 100vh above the current viewport, and selects the closest section, or the line at the top of the hidden previous viewport to scroll to when the user scrolls up.

Play Scroll View v2: Scroll up

---

src/components/play/scroll/ScrollPlayContent.tsx

Padding the bottom of the song with 100vh. This gives the last scroll a bit more room to jump and will make the last scroll less confusing.

Play Scroll View: last scroll behaviour

---

src/components/play/scroll/ScrollablePlayLine.tsx

Making the next scroll line candidate viewport a bit smaller (25% -75% instead of 15% -75%). It seems to not be to scroll a small amount even if it's section aligned.

Play Scroll View: narrow next scroll line viewport

---

src/components/play/scroll/HighlightBorderBox.tsx
src/components/play/scroll/ScrollPlayContent.tsx
src/components/play/scroll/highlightBorderContext.tsx
src/components/play/scroll/highlightColourContext.tsx

Trying a new visual design, rotating the colours of the highlight so that it gives more of a visual cue to the user that the newly highlighted line is different than the one just highlighted (and is fading).
This implementation adds a context on top which will keep cycling the colours each time one is fetched.

Play Scroll View: 3 colour rotation for highlighting borders

---

src/components/track_player/common.tsx

Fixing an unsightly bug:
If the track player is up but the user is hovering over a line, the tool tip hover controls can show up over the track player, which makes no sense visually.
Fix here is to give the track player a higher z-index than the hover menu. TBD if this is the right fix.

Fix line controls occluding track player

---

src/components/track_player/JamStation.tsx
src/components/track_player/common.tsx

Fixing the sketchy fix of https://github.com/veedubyou/chord-paper-fe/pull/318
Interestingly enough, the issue only happens on Chrome and not Firefox. After boosting just the z index of the player, some components such as the select menu for the track selector gets drawn behind the player instead of in front.
Fix here is to modify the theme for the track player portion such that all components below will inherit a boosted z index, and so components like the Select for the track list selector will have a higher z index than the player component, but the player component will still have a higher z index than the editing controls.

Fix tracklist selector hidden by player component in Chrome

---

src/components/track_player/MultiTrackPlayer.tsx

This is a Material UI issue. Just a workaround for now, hopefully it's stable.
The issue:
Looking normal:
When the select menu is focused and the entire player shifts some amount to the right because the scrollbar disappeared:

Prevent track player shifting right on select menu focus

---

src/components/play/common/PlayLine.tsx
src/components/play/scroll/ScrollPlayContent.tsx

Fixing one of a few perf regressions as part of something that was broke in the MUI5 upgrade.
In the play scroll view, there's an entire rerender of the page's contents whenever the highlight changes, because of the callback functions that get created fresh and tunneled down. These really don't need to be brand new functions for setting the ref methods, so I attached them as methods on the ViewportLine object itself in the beginning to avoid unnecessary rerenders.

Perf Regression: Scroll View

---

src/components/SideMenu.tsx

Tiny addition that may be unnecessary, but the side menu rerenders for every change to the song itself which seems wildly unnecessary.

Minor perf bump: memoizing side menu

---

src/components/track_player/internal_player/usePlayerControls.ts

Scoping this player workaround. Sometimes the stem players get out of sync and I wonder if it's due to this workaround, however since there's no reliable repro for the player getting out of sync I'd like to just try applying this fix and seeing if it alleviates the symptoms.
This is technically more aligned with the initial intention since the workaround is applied for Youtube links only.

Scope player workaround

---

src/components/edit/menu/TransposeMenu.tsx

MUI 5 somehow broke the labels for these select fields in the transpose menu (they would cut off at the length of the select component instead of causing the select component to lengthen). Instead of trying to figure out how to fix it I opted to use another form of input labels that looked even better.

Fix transpose menu labels

---

src/common/ChordModel/ChordLine.ts
src/common/ChordModel/ChordSong.ts
src/common/ChordModel/Section.ts
src/components/PlayerSectionContext.tsx
src/components/edit/ChordPaper.tsx
src/components/edit/ChordPaperBody.tsx
src/components/edit/Line.tsx
src/components/edit/LineWithHoverMenu.tsx
src/components/edit/LineWithLyricInput.tsx
src/components/edit/LineWithSection.tsx
src/components/edit/LineWithSectionHighlight.tsx
src/components/edit/NewLine.tsx
src/components/edit/menu/TransposeMenu.tsx
src/components/play/Play.tsx
src/components/track_player/JamStation.tsx
src/components/track_player/internal_player/ControlPane.tsx
src/components/track_player/internal_player/single/SingleTrackPlayer.tsx
src/components/track_player/internal_player/stem/LoadedStemTrackPlayer.tsx
src/components/track_player/internal_player/usePlayerControls.ts

Since pulling out the section label from the player, I've decided to add the indicator for which section is currently playing onto the chord paper itself.
This works by providing another context provider which states which section is currently at play, and all the lines will respond to it by adjusting its background color. Thankfully since the internal contents are memoized, the rerender of these colors is rather cheap.

Section highlighting

---

src/common/ChordModel/ChordLine.ts
src/common/ChordModel/ChordSong.ts
src/components/display/SectionHighlight.tsx
src/components/edit/ChordPaperBody.tsx
src/components/play/scroll/ScrollPlayContent.tsx
src/components/reducer/reducer.ts
tsconfig.json

Adding a check to make sure that all the sections have monotonically increasing time in the order they appear.
In addition to the change itself, I also had to change the reducer to allow for bailing out of a state change if it fails validation. Turns out these cases already existed in the split/merge line functionality, but I hadn't handled it gracefully - it would add an additional entry in the undo stack of the same state.

Validate timestamped sections ordering

---

src/components/PlayerSectionContext.tsx
src/components/PlayerTimeContext.tsx
src/components/edit/TimeInput.tsx
src/components/track_player/internal_player/advanced_controls/ABLoopControl.tsx

This change prevents section highlighting in 2 scenarios:
-a song isn't playing
-a song is at the beginning
Both of these may indicate that the user hasn't started playing the song yet and it may be a confusing UI to highlight something that the user hasn't interacted with.

Prevent setting section without song playing or at beginning of song

---

src/components/edit/menu/ChordPaperMenu.tsx

The delete button shows up in songs for people who aren't owners. The backend will still refuse the unauthorized request but it's a confusing UI to offer a button that never works, so this change disables that button for non-owners.

Disable delete button for non-owners

---

src/components/PlayerSectionContext.tsx
src/components/display/LineWithSectionHighlight.tsx
src/components/track_player/JamStation.tsx
src/components/track_player/MicroPlayer.tsx
src/components/track_player/MultiTrackPlayer.tsx
src/components/track_player/TrackPlayer.tsx
src/components/track_player/internal_player/ControlPane.tsx
src/components/track_player/internal_player/TransportControl.tsx
src/components/track_player/internal_player/advanced_controls/ABLoopControl.tsx
src/components/track_player/internal_player/advanced_controls/AdvancedControls.tsx
src/components/track_player/internal_player/advanced_controls/TempoControl.tsx
src/components/track_player/internal_player/advanced_controls/TransposeControl.tsx
src/components/track_player/internal_player/single/SingleTrackPlayer.tsx
src/components/track_player/internal_player/stem/LoadedStemTrackPlayer.tsx
src/components/track_player/internal_player/stem/StemTrackControlPane.tsx
src/components/track_player/internal_player/usePlayerControls.ts

A performance pass on the track player. Classic reduce the amount of renders performance pass. Issue was that a render on the track player was happening around every second, now it's been reduced to once per section and also lightening the render during those times.
Several things to make that happen:
-remove the currentTime state on usePlayerControls and use the ref exclusively instead as the source of truth. this way when an update happens, no rerender happens. this does force some of the consumers to set their own timers instead of waiting for a rerender, but the only place that needs it is the stem player for synchronization, and its reaction to the changing time is not a render anyway
-memoizing pretty much everything, including the props that come out of usePlayerControls and a lot …

Improve track player performance

---

src/components/PlayerSectionContext.tsx

Fixes https://github.com/veedubyou/chord-paper-fe/issues/367
The issue stems from the list and the current section provided by the PlayerSectionContext being out of sync. Example scenario:
time sections are size 3
current section is index 2 (i.e. the last one)
The user deletes the last section:
time sections are size 2
current section is index 2
therefore out of bounds
Ideally the context always provides a valid section - the fix is when the time sections change, reevaluate the current section. This is done outside of useEffect in the render to make sure there is no out of sync issues - that the current section is compatible with the list.

Crash fix: update PlayerSectionContext when sections change

---

src/common/ChordModel/tracks/SplitStemRequest.ts

Small quality of life improvement - fill in a default label for split requests so that the user doesn't have to type in something inane all the time.

add default labels for split requests

---

src/components/edit/TimeInput.tsx

The "set current time for section" button has a weird race where it would defocus the time input before the current time is set. Trying these changes to see if this fixes it.

Try fixing time button race

---

src/common/ChordModel/Lyric.ts
src/common/ChordModel/test/Lyric.test.ts
src/components/display/Lyric.tsx
src/components/reducer/reducer.ts

When copying and pasting lyrics, the copied lyrics may sometimes include empty lines of whitespaces from e.g. paragraph separation from the lyric source. This is rarely what the user would want as separation is provided by sections, and empty lines provide no material for annotating chords.
This change filters out these extraneous lines upon lyric pasting.

Remove any empty lines on lyric paste

---

src/common/ChordModel/ChordLine.ts
src/components/display/SectionHighlight.tsx
src/components/play/scroll/ScrollPlayContent.tsx
src/components/play/scroll/ScrollablePlayLine.tsx

Adding an auto scroll feature to the play scroll view. When playing the song, when the next section comes into play, it will automatically scroll to the head of that section.
This required that I split the viewport margins into current, current top (top 25/30% of the screen), and current bottom (bottom 25/30% of the screen) so that it can be composed more independently.

Auto scroll

---

src/components/track_player/internal_player/stem/LoadedStemTrackPlayer.tsx

Fairly often enough, Tonejs and the player gets out of sync in terms of player state - the player UI keeps going but nothing is playing. Suspicion is that some handling is causing a missing state. Adding periodic logging every 5 seconds to see what's going on. The reason this is done is because it's hard to reproduce this locally, but it happens easily in prod.

Add periodic logs to Tone js in prod
